# IMPORTANT: all scripts can run only if they end with cls which stands for `Chat Logger Script`

# using # as the first word makes it a comment
# when using scriots you need to make a newline for each command
# when using scripts you don't need to use the prefix
# scripts have a command called

delay 1

# which uses ticks as a delay until the next command. Example: 

f on

delay 100

f off

# This will start the forward function and stop it after 100 ticks (5 seconds)
# you can also make a loop by putting the runscript function with the name of the same file making it run itself